FROM python:3.6

WORKDIR /toktok_in_docker

COPY requirements.txt /toktok_in_docker/requirements.txt

RUN pip install -r requirements.txt

COPY . /toktok_in_docker

ENTRYPOINT ["gunicorn"]
CMD ["wsgi_prod_docker:app","--bind","0.0.0.0:4100"]
