version: '2.1'
services:
  backend:
    container_name: ${APP}-backend
    build:
      context: ${APP_PATH}
      dockerfile: ${DF_FOLDER_SUBPATH}/Dockerfile.gunicorn-prod
    restart: always
    ports:
      - "4100:4100"
